"""empty message

Revision ID: 9f9b1e3981fe
Revises: cca7c9f1293f
Create Date: 2024-07-25 21:40:38.683864

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f9b1e3981fe"
down_revision = "cca7c9f1293f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("balance", sa.Integer(), nullable=True))
    op.execute("UPDATE users SET balance = 100 WHERE balance IS NULL")
    op.alter_column("users", "balance", existing_type=sa.Integer(), nullable=False)
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "balance")
    # ### end Alembic commands ###
