"""Add operation and deleted columns to record

Revision ID: 45850a941374
Revises: 9937e0baf906
Create Date: 2024-08-26 16:17:58.311278

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45850a941374"
down_revision = "9937e0baf906"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records",
        sa.Column(
            "deleted", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "records", sa.Column("operation_text", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "deleted")
    op.drop_column("records", "operation")
    # ### end Alembic commands ###
