"""Generate Models

Revision ID: cca7c9f1293f
Revises: 2b7380507a71
Create Date: 2024-07-23 11:31:59.859295

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cca7c9f1293f"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "ADDITION",
                "SUBSTRACTION",
                "MULTIPLICATION",
                "DIVISION",
                "SQUARE",
                "RANDOM",
                name="operationenum",
            ),
            nullable=False,
        ),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("user_balance", sa.Integer(), nullable=False),
        sa.Column("operation_response", sa.String(length=200), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=200), nullable=False),
        sa.Column("password", sa.String(length=200), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="statusenum"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "dummy_model", "name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dummy_model", "name", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.drop_table("users")
    op.drop_table("records")
    op.drop_table("operations")
    # ### end Alembic commands ###
